In [19]:
import numpy as np

# basic matrix cmd:

In [2]:
mx_1s= np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
mx_1s = np.ones((4),dtype=int)
print(mx_1s)

[1 1 1 1]


In [7]:
mx_1s.dtype

dtype('int32')

In [8]:
mx_1s = np.ones((3,5))
print(mx_1s)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
mx_1s.dtype

dtype('float64')

In [11]:
mx_0s=np.zeros((2,3))
print(mx_0s)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
mx_0s=np.zeros((2,3) , dtype=int)
print(mx_0s)

[[0 0 0]
 [0 0 0]]


In [13]:
mx_0s=np.zeros((2,3) , dtype=bool)
print(mx_0s)

[[False False False]
 [False False False]]


In [14]:
mx_0s=np.zeros((2,3) , dtype=str)
print(mx_0s)

[['' '' '']
 ['' '' '']]


In [16]:
em_str=''
print(bool(em_str))


False


In [17]:
em_mx =np.empty((3,4))
print(em_mx)

[[1.01107843e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.16709769e-312 1.32656714e-075 1.43710628e-071 2.34442841e-056]
 [1.10844689e-047 1.42024661e+161 1.00105155e+165 1.00713899e-046]]


In [18]:
#empty matrix have any data in it it cannt be empty 