In [4]:
import numpy as np

In [5]:
arr_id = np.array([1,2,3,4])
print(arr_id)

[1 2 3 4]


In [6]:
type(arr_id)

numpy.ndarray

In [9]:
arr_id.ndim

1

In [10]:
#creating 2d array

In [11]:
arr_2d= np.array([[1,2,3,4],[3,2,4,2]])
print(arr_2d)

[[1 2 3 4]
 [3 2 4 2]]


In [12]:
type(arr_2d)

numpy.ndarray

In [14]:
arr_2d.size

8

In [15]:
arr_2d.dtype

dtype('int32')

In [16]:
arr_id.dtype

dtype('int32')

In [17]:
arr_2d.shape

(2, 4)

In [18]:
#(2,4) =(rows,coloumn)

In [19]:
arr_2d.ndim

2